/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import dao.PermissaoDao;
import entidade.Usuario;
import functions.Funcoes;
import functions.Mensagem;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author mateus
 */
public class TelaPermissao extends javax.swing.JDialog {

    private Usuario usuario;
    private PermissaoDao peDAO = new PermissaoDao();
    private ArrayList<String> perm = new ArrayList();
    
    //acoes
    private final String acessar = "Acessar";
    private final String editar = "Editar";
    private final String excluir = "Excluir";
    private final String salvar = "Salvar";
    private final String buscar = "Buscar";
    private final String limparBusca = "LimparBusca";
    
    //telas
    private final String telaMarca = "marca";

    /**
     * Creates new form TelaPermissao
     */
    public TelaPermissao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public TelaPermissao(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        preenchePermissoesMarca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cbxAcessar = new javax.swing.JCheckBox();
        cbxBtnSalvar = new javax.swing.JCheckBox();
        cbxBtnEditar = new javax.swing.JCheckBox();
        cbxBtnExcluir = new javax.swing.JCheckBox();
        cbxBtnBuscar = new javax.swing.JCheckBox();
        cbxBtnLimparBusca = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxAcessar.setText("Acessar");

        cbxBtnSalvar.setText("Botão Salvar");

        cbxBtnEditar.setText("Botão Editar");

        cbxBtnExcluir.setText("Botão Excluir");

        cbxBtnBuscar.setText("Botão Buscar");

        cbxBtnLimparBusca.setText("Botão Limpar Busca");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxAcessar)
                    .addComponent(cbxBtnSalvar)
                    .addComponent(cbxBtnEditar)
                    .addComponent(cbxBtnExcluir)
                    .addComponent(cbxBtnBuscar)
                    .addComponent(cbxBtnLimparBusca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxAcessar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxBtnSalvar)
                .addGap(4, 4, 4)
                .addComponent(cbxBtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxBtnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxBtnLimparBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Marca", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificaPermissoes(JCheckBox cbx, String regra, String tela) {
        boolean ok = false;
        if (cbx.isSelected()) {
            if (!peDAO.consultarPermissao(regra, tela)) {
                ok = Funcoes.salvarPermissao(regra, usuario, tela);
            } else {
                ok = true;
            }
        } else {
            if (peDAO.consultarPermissao(regra, tela)) {
                ok = peDAO.excluir(regra, tela);
            } else {
                ok = true;
            }
        }
        return ok;
    }

    private void preenchePermissoesMarca() {
        perm = peDAO.consultarPermissoes(telaMarca);
        for (int i = 0; i < perm.size(); i++) {
            if (perm.get(i).equals(acessar)) {
                cbxAcessar.setSelected(true);
            }
            if (perm.get(i).equals(editar)) {
                cbxBtnEditar.setSelected(true);
            }
            if (perm.get(i).equals(salvar)) {
                cbxBtnSalvar.setSelected(true);
            }
            if (perm.get(i).equals(excluir)) {
                cbxBtnExcluir.setSelected(true);
            }
            if (perm.get(i).equals(buscar)) {
                cbxBtnBuscar.setSelected(true);
            }
            if (perm.get(i).equals(limparBusca)) {
                cbxBtnLimparBusca.setSelected(true);
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean ok;
        boolean marca = true;
        ok = verificaPermissoes(cbxAcessar, acessar, telaMarca);
        if (!ok == true) {
            marca = false;
        }
        ok = verificaPermissoes(cbxBtnEditar, editar, telaMarca);
        if (!ok == true) {
            marca = false;
        }
        ok = verificaPermissoes(cbxBtnSalvar, salvar, telaMarca);
        if (!ok == true) {
            marca = false;
        }
        ok = verificaPermissoes(cbxBtnExcluir, excluir, telaMarca);
        if (!ok == true) {
            marca = false;
        }
        ok = verificaPermissoes(cbxBtnBuscar, buscar, telaMarca);
        if (!ok == true) {
            marca = false;
        }
        ok = verificaPermissoes(cbxBtnLimparBusca, limparBusca, telaMarca);
        if (!ok == true) {
            marca = false;
        }

        if (marca == true) {
            Mensagem.informacao("Permissões adicionadas com sucesso!", this);
        } else {
            Mensagem.erro("Ocorreu um erro ao salvar as permissões!", this);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPermissao dialog = new TelaPermissao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxAcessar;
    private javax.swing.JCheckBox cbxBtnBuscar;
    private javax.swing.JCheckBox cbxBtnEditar;
    private javax.swing.JCheckBox cbxBtnExcluir;
    private javax.swing.JCheckBox cbxBtnLimparBusca;
    private javax.swing.JCheckBox cbxBtnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
